### ISSUE TITLE
xxx

### ISSUE THREAD

**Issue by Drunghao** [zzsdoo/xuexiqiangguo_tiku#9]
开创“长吉体”诗歌的是（李贺）

**Comment by Drunghao** [comment]
关于地理上的阴阳的解释，正确的是（山的北面为阴，水的北面为阳）

**Comment by youngchen1987** [comment]
![image](https://user-images.githubusercontent.com/11566474/60701194-824deb00-9f2d-11e9-9c29-b6497a9cb663.png)
把题图弄到小工具 更方便了
